
GET http://localhost:3000/login

{
    "email" : "mail@mail.com",
    "password" : "secret"
}

###

GET http://localhost:3000/verify
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QiLCJwYXNzd29yZCI6InNlY3JldCIsImlhdCI6MTU5NTQyNTMyOH0.Ppeg96n7bXy3AMAWAsZIKHuaB_pSyIvWj5lHXbhUKH4n1woSaWQXW3m17Vw3pBB6ZV_DfBJrOxI4cwUmUie0aDa-MNZaPnuizxoMQkae3Ygve3JW9DCYRJ8h7Nid06L2OUViBOMwkfyeVpbOPt2XB379hdAkf05VP6U4mthJ6RSeZBZ-ML_yBHmVplB3n1kjT76-RI8US59qFN80MeZ6tVBjUegUZAp-d7sUc1MUbsVkj7Mb8y3OC8z62oUsm9TGoX-b5uBSUH8qxNqjgGjuIIoqA9lTrIPKMY_bfPXvNYizdR3JuXCgz84xU_lv3jK1V9q01Rrn-J27jXZW-fUjUg